version: '2'
services:
  c-oad-nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./nginx/:/etc/nginx/
      - ../log:/opt/nginx-load-balancer/log
      - ../data:/usr/share/nginx/html/data
      - ../docs/_build/html:/usr/share/nginx/html/docs
    restart: always
    networks:
      - nginx-load-balancer
      - oad
  c-oad-app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/opt/oad
    restart: always
    networks:
      - oad
networks:
  oad:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
